[workspace]
members = ["crates/tensorfs-core", "crates/tensorfsd"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/cozy-creator/tensorfs"
rust-version = "1.91"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "2.0"
unicode-normalization = "0.1.24"
