package tensorfs

// Contract documents (tensorfs-contract-v1), parsed and digested in Go so
// tensorhub can STORE + FORWARD extracted documents generically: parse-validate
// at publish (typed refusal on garbage), verify a claimed digest stamp against
// the document, store it verbatim. No pattern introspection, no conversion
// planning — those run where tensorfs runs.
//
// The validator mirrors the Rust one refusal for refusal, and the canonical
// rendering — the digest input — byte for byte. The agreement is enforced by
// the shared corpus in spec/v1/contract-vectors/, generated by Rust and run by
// both CIs; that corpus, not discipline, is the cross-language sync mechanism.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// ContractFormat is the one document format tag.
const ContractFormat = "tensorfs-contract-v1"

// ContractError is a typed refusal with the stable kebab-case reason label
// shared with the Rust validator's ContractError::reason.
type ContractError struct {
	// Reason is one of: json, format, name, version, identity, dtype,
	// no-tensors, pattern, duplicate, role-holes, fusion, permute, set.
	Reason  string
	Message string
}

func (e *ContractError) Error() string {
	return "contract: " + e.Reason + ": " + e.Message
}

func contractRefuse(reason, message string) error {
	return &ContractError{Reason: reason, Message: message}
}

// Contract is one validated layout contract: named when it comes from the
// curated library, nameless — identified by digest alone — when it is an
// author-constructed custom.
type Contract struct {
	name        string // "" when nameless
	version     uint32 // 0 when nameless
	description string
	dtype       string // "" when absent
	tensors     []contractTensor
	setNames    []string // sorted, the canonical set order
	sets        map[string][]contractPattern
}

type contractTensor struct {
	role     contractPattern
	pattern  contractPattern
	dtypes   []string
	rank     *uint64
	required bool
	fusion   *contractFusion
	permute  *contractPermute
}

type contractFusion struct {
	groups uint64
	parts  []contractFusionPart
}

type contractFusionPart struct {
	role  string
	share uint64
}

type contractPermute struct {
	view []permuteDim
	axes []uint64
}

const (
	dimLiteral = iota
	dimAxis
	dimAuto
)

type permuteDim struct {
	kind    int
	literal uint64
	axis    uint64
	divisor uint64
}

// contractPattern is literal text with {i} integer holes; parsing mirrors the
// Rust Pattern (adjacent holes, a digit after a hole, and stray braces all
// refuse).
type contractPattern struct {
	text  string
	holes int
}

func parseContractPattern(text string) (contractPattern, error) {
	refuse := func() (contractPattern, error) {
		return contractPattern{}, contractRefuse("pattern", strconv.Quote(text))
	}
	if len(text) == 0 || len(text) > 512 {
		return refuse()
	}
	holes := 0
	lastWasHole := false
	rest := text
	for len(rest) > 0 {
		at := strings.Index(rest, "{i}")
		if at < 0 {
			if strings.ContainsAny(rest, "{}") {
				return refuse()
			}
			lastWasHole = false
			break
		}
		if at > 0 {
			if strings.ContainsAny(rest[:at], "{}") {
				return refuse()
			}
		} else if lastWasHole {
			// Adjacent holes cannot be separated by any input.
			return refuse()
		}
		holes++
		lastWasHole = true
		rest = rest[at+3:]
		if len(rest) > 0 && rest[0] >= '0' && rest[0] <= '9' {
			// A digit after a hole makes the split ambiguous.
			return refuse()
		}
	}
	return contractPattern{text: text, holes: holes}, nil
}

// --- raw document shape ---------------------------------------------------

type rawContract struct {
	Format      *string             `json:"format"`
	Name        *string             `json:"name"`
	Version     *uint32             `json:"version"`
	Description *string             `json:"description"`
	Dtype       *string             `json:"dtype"`
	Tensors     *[]rawTensor        `json:"tensors"`
	Sets        map[string][]string `json:"sets"`
}

type rawTensor struct {
	Role     *string     `json:"role"`
	Pattern  *string     `json:"pattern"`
	Dtypes   []string    `json:"dtypes"`
	Rank     *uint64     `json:"rank"`
	Required *bool       `json:"required"`
	Fusion   *rawFusion  `json:"fusion"`
	Permute  *rawPermute `json:"permute"`
}

type rawFusion struct {
	Axis   *uint64    `json:"axis"`
	Groups *uint64    `json:"groups"`
	Parts  *[]rawPart `json:"parts"`
}

type rawPart struct {
	Role  *string `json:"role"`
	Share *uint64 `json:"share"`
}

type rawPermute struct {
	View *[]any    `json:"view"`
	Axes *[]uint64 `json:"axes"`
}

// ParseContract parses and validates one tensorfs-contract-v1 document.
func ParseContract(document []byte) (*Contract, error) {
	decoder := json.NewDecoder(bytes.NewReader(document))
	decoder.DisallowUnknownFields()
	decoder.UseNumber()
	var raw rawContract
	if err := decoder.Decode(&raw); err != nil {
		return nil, contractRefuse("json", err.Error())
	}
	var trailing any
	if err := decoder.Decode(&trailing); err == nil || err.Error() != "EOF" {
		return nil, contractRefuse("json", "trailing data after the document")
	}
	// Required fields mirror the Rust serde derivation: absence is a JSON
	// shape error, not a semantic refusal.
	if raw.Format == nil || raw.Tensors == nil {
		return nil, contractRefuse("json", "missing format or tensors")
	}
	if *raw.Format != ContractFormat {
		return nil, contractRefuse("format", *raw.Format)
	}

	contract := &Contract{sets: map[string][]contractPattern{}}
	switch {
	case raw.Name == nil && raw.Version == nil:
		// Nameless: an author-constructed custom, identified by digest.
	case raw.Name != nil && raw.Version != nil:
		if !isContractName(*raw.Name) {
			return nil, contractRefuse("name", strconv.Quote(*raw.Name))
		}
		if *raw.Version == 0 {
			return nil, contractRefuse("version", "must be at least 1")
		}
		contract.name, contract.version = *raw.Name, *raw.Version
	default:
		return nil, contractRefuse("identity", "name and version travel together or not at all")
	}
	if raw.Description != nil {
		contract.description = *raw.Description
	}
	if raw.Dtype != nil {
		if !isContractDtype(*raw.Dtype) {
			return nil, contractRefuse("dtype", strconv.Quote(*raw.Dtype))
		}
		contract.dtype = *raw.Dtype
	}
	if len(*raw.Tensors) == 0 {
		return nil, contractRefuse("no-tensors", "a contract declares at least one tensor")
	}

	patterns := map[string]bool{}
	roles := map[string]bool{}
	for _, rawEntry := range *raw.Tensors {
		if rawEntry.Role == nil || rawEntry.Pattern == nil {
			return nil, contractRefuse("json", "a tensor declares role and pattern")
		}
		pattern, err := parseContractPattern(*rawEntry.Pattern)
		if err != nil {
			return nil, err
		}
		role, err := parseContractPattern(*rawEntry.Role)
		if err != nil {
			return nil, err
		}
		if role.holes != pattern.holes {
			return nil, contractRefuse("role-holes", strconv.Quote(role.text))
		}
		if patterns[pattern.text] {
			return nil, contractRefuse("duplicate", strconv.Quote(pattern.text))
		}
		patterns[pattern.text] = true
		if roles[role.text] {
			return nil, contractRefuse("duplicate", strconv.Quote(role.text))
		}
		roles[role.text] = true

		entry := contractTensor{
			role:     role,
			pattern:  pattern,
			dtypes:   rawEntry.Dtypes,
			rank:     rawEntry.Rank,
			required: rawEntry.Required == nil || *rawEntry.Required,
		}
		if rawEntry.Fusion != nil {
			fusion, err := validateFusion(pattern.text, rawEntry.Fusion)
			if err != nil {
				return nil, err
			}
			entry.fusion = fusion
		}
		if rawEntry.Permute != nil {
			permute, err := validatePermute(pattern.text, entry.fusion != nil, rawEntry.Permute)
			if err != nil {
				return nil, err
			}
			entry.permute = permute
		}
		contract.tensors = append(contract.tensors, entry)
	}

	for name, members := range raw.Sets {
		if len(members) == 0 {
			return nil, contractRefuse("set", strconv.Quote(name))
		}
		compiled := make([]contractPattern, 0, len(members))
		for _, member := range members {
			pattern, err := parseContractPattern(member)
			if err != nil {
				return nil, err
			}
			compiled = append(compiled, pattern)
		}
		contract.sets[name] = compiled
		contract.setNames = append(contract.setNames, name)
	}
	sort.Strings(contract.setNames)
	return contract, nil
}

func validateFusion(pattern string, raw *rawFusion) (*contractFusion, error) {
	refuse := func() (*contractFusion, error) {
		return nil, contractRefuse("fusion", strconv.Quote(pattern))
	}
	if raw.Axis == nil || raw.Parts == nil {
		return nil, contractRefuse("json", "a fusion declares axis and parts")
	}
	groups := uint64(1)
	if raw.Groups != nil {
		groups = *raw.Groups
	}
	// Only the outer axis concatenates; a single part in a single group is
	// the whole tensor, which is not a fusion.
	if *raw.Axis != 0 || groups == 0 || len(*raw.Parts) == 0 ||
		(groups == 1 && len(*raw.Parts) < 2) {
		return refuse()
	}
	seen := map[string]bool{}
	parts := make([]contractFusionPart, 0, len(*raw.Parts))
	for _, part := range *raw.Parts {
		if part.Role == nil || part.Share == nil {
			return nil, contractRefuse("json", "a fusion part declares role and share")
		}
		if *part.Share == 0 || seen[*part.Role] {
			return refuse()
		}
		seen[*part.Role] = true
		// An unnamed part is only meaningful as the sole part of an
		// interleaved slice: it IS the declared role.
		if *part.Role == "" && len(seen) > 1 {
			return refuse()
		}
		parts = append(parts, contractFusionPart{role: *part.Role, share: *part.Share})
	}
	if len(parts) > 1 {
		for _, part := range parts {
			if part.role == "" {
				return refuse()
			}
		}
	}
	return &contractFusion{groups: groups, parts: parts}, nil
}

func validatePermute(pattern string, fused bool, raw *rawPermute) (*contractPermute, error) {
	refuse := func() (*contractPermute, error) {
		return nil, contractRefuse("permute", strconv.Quote(pattern))
	}
	if raw.View == nil || raw.Axes == nil {
		return nil, contractRefuse("json", "a permute declares view and axes")
	}
	// A permute inside a fused tensor would mean its seam runs are NOT the
	// split packaging's bytes, which is the one thing a seam promises.
	if fused {
		return refuse()
	}
	if len(*raw.View) < 2 || len(*raw.Axes) != len(*raw.View) {
		return refuse()
	}
	seen := make([]bool, len(*raw.Axes))
	identity := true
	for at, axis := range *raw.Axes {
		if axis >= uint64(len(seen)) || seen[axis] {
			return refuse()
		}
		seen[axis] = true
		if uint64(at) != axis {
			identity = false
		}
	}
	if identity {
		// The identity permute is the absence of one.
		return refuse()
	}
	view := make([]permuteDim, 0, len(*raw.View))
	for _, value := range *raw.View {
		dim, ok := parsePermuteDim(value)
		if !ok {
			return refuse()
		}
		view = append(view, dim)
	}
	return &contractPermute{view: view, axes: *raw.Axes}, nil
}

func parsePermuteDim(value any) (permuteDim, bool) {
	var text string
	switch typed := value.(type) {
	case json.Number:
		literal, err := strconv.ParseUint(typed.String(), 10, 64)
		if err != nil || literal == 0 {
			return permuteDim{}, false
		}
		return permuteDim{kind: dimLiteral, literal: literal}, true
	case string:
		text = typed
	default:
		return permuteDim{}, false
	}
	if text == "auto" {
		return permuteDim{kind: dimAuto}, true
	}
	if literal, err := strconv.ParseUint(text, 10, 64); err == nil {
		if literal == 0 {
			return permuteDim{}, false
		}
		return permuteDim{kind: dimLiteral, literal: literal}, true
	}
	head, divisorText, divided := strings.Cut(text, "/")
	divisor := uint64(1)
	if divided {
		parsed, err := strconv.ParseUint(divisorText, 10, 64)
		if err != nil || parsed == 0 {
			return permuteDim{}, false
		}
		divisor = parsed
	}
	inner, isShape := strings.CutPrefix(head, "shape[")
	if !isShape {
		return permuteDim{}, false
	}
	digits, closed := strings.CutSuffix(inner, "]")
	if !closed {
		return permuteDim{}, false
	}
	axis, err := strconv.ParseUint(digits, 10, 64)
	if err != nil {
		return permuteDim{}, false
	}
	return permuteDim{kind: dimAxis, axis: axis, divisor: divisor}, true
}

func isContractName(name string) bool {
	return name != "" && len(name) <= TFM1MaxContractNameBytes && isTFM1ContractName(name)
}

// isContractDtype mirrors the Rust spelling check: torch-style, lowercase,
// bounded — a shape, not an enum.
func isContractDtype(dtype string) bool {
	if dtype == "" || len(dtype) > 32 {
		return false
	}
	for _, character := range []byte(dtype) {
		lower := character >= 'a' && character <= 'z'
		digit := character >= '0' && character <= '9'
		if !lower && !digit && character != '_' {
			return false
		}
	}
	return true
}

// --- identity --------------------------------------------------------------

// Name is the library name, or "" for an anonymous custom.
func (c *Contract) Name() string { return c.name }

// Version is the library version; 0 for an anonymous custom.
func (c *Contract) Version() uint32 { return c.version }

// Description is the free-text description, possibly empty.
func (c *Contract) Description() string { return c.description }

// Dtype is the optional top-level load dtype, "" when undeclared.
func (c *Contract) Dtype() string { return c.dtype }

// Digest is the SHA-256 of the canonical rendering, bare lowercase hex —
// identical to the Rust Contract::digest and the Python Contract.digest.
func (c *Contract) Digest() string {
	sum := sha256.Sum256([]byte(c.canonical()))
	return hex.EncodeToString(sum[:])
}

// Stamp is name@version for a library document, sha256:<hex> for a custom —
// exactly the spelling a TFM1 snapshot records.
func (c *Contract) Stamp() string {
	if c.name != "" {
		return fmt.Sprintf("%s@%d", c.name, c.version)
	}
	return "sha256:" + c.Digest()
}

// canonical mirrors the Rust rendering BYTE FOR BYTE: same lines, same field
// order, same omission of absent fields. Any divergence fails the shared
// corpus digests.
func (c *Contract) canonical() string {
	var b strings.Builder
	b.WriteString(ContractFormat)
	b.WriteByte('\n')
	if c.name != "" {
		fmt.Fprintf(&b, "name=%s\nversion=%d\n", c.name, c.version)
	}
	if c.dtype != "" {
		b.WriteString("dtype=")
		b.WriteString(c.dtype)
		b.WriteByte('\n')
	}
	for _, tensor := range c.tensors {
		rank := "any"
		if tensor.rank != nil {
			rank = strconv.FormatUint(*tensor.rank, 10)
		}
		fmt.Fprintf(
			&b,
			"tensor role=%s pattern=%s rank=%s required=%t dtypes=%s",
			tensor.role.text,
			tensor.pattern.text,
			rank,
			tensor.required,
			strings.Join(tensor.dtypes, ","),
		)
		if tensor.permute != nil {
			b.WriteString(" permute=")
			for _, dim := range tensor.permute.view {
				switch dim.kind {
				case dimLiteral:
					b.WriteString(strconv.FormatUint(dim.literal, 10))
				case dimAuto:
					b.WriteString("auto")
				case dimAxis:
					fmt.Fprintf(&b, "shape[%d]/%d", dim.axis, dim.divisor)
				}
				b.WriteByte(',')
			}
			// The Rust side renders the axes list with Debug formatting.
			b.WriteString(":[")
			for at, axis := range tensor.permute.axes {
				if at > 0 {
					b.WriteString(", ")
				}
				b.WriteString(strconv.FormatUint(axis, 10))
			}
			b.WriteByte(']')
		}
		if tensor.fusion != nil {
			fmt.Fprintf(&b, " fusion=groups:%d,", tensor.fusion.groups)
			for _, part := range tensor.fusion.parts {
				fmt.Fprintf(&b, "%s:%d,", part.role, part.share)
			}
		}
		b.WriteByte('\n')
	}
	for _, name := range c.setNames {
		b.WriteString("set ")
		b.WriteString(name)
		b.WriteByte('=')
		for _, pattern := range c.sets[name] {
			b.WriteString(pattern.text)
			b.WriteByte(',')
		}
		b.WriteByte('\n')
	}
	return b.String()
}
