"""Type stubs for the compiled extension module.

PyO3 emits no typing information, so this file is what carries `tensorfs`'s
strict-mypy guarantee across the extension boundary. It ships in the wheel
beside `py.typed`. Every signature here is checked against the real module at
runtime by `python/tests/test_native.py::test_stub_matches_the_extension`.

Digests are bare lowercase 64-character hex -- the same spelling as
`tensorfs.CASRef.digest`. The algorithm-tagged form `sha256:<hex>` is accepted
wherever a digest is taken and is never returned.
"""

from collections.abc import Mapping, Sequence
from os import PathLike
from pathlib import Path
from typing import Final

# The `str | _CarriesDocument` / `str | _CarriesStamp` Protocols stood here for
# `tensorfs.Contract`, which is deleted. Nothing in Python carries a v1 document
# any more, so every one of these parameters is a plain string.

__version__: Final[str]

MAX_OBJECT_SIZE: Final[int]
STUB_MAGIC: Final[bytes]
MAX_PACK_PAYLOAD: Final[int]
MAX_PACK_OBJECTS: Final[int]
MAX_FILE_RECORDS: Final[int]
MAX_PATH_BYTES: Final[int]
MAX_SYMLINK_TARGET_BYTES: Final[int]

class TensorfsError(Exception): ...
class StoreError(TensorfsError): ...
class FormatError(TensorfsError): ...
class PlanError(TensorfsError): ...
class LayoutError(TensorfsError): ...

class AdmittedObject:
    @property
    def digest(self) -> str: ...
    @property
    def length(self) -> int: ...
    @property
    def preexisting(self) -> bool: ...

class TempCollection:
    @property
    def examined(self) -> int: ...
    @property
    def deleted(self) -> int: ...
    @property
    def bytes_deleted(self) -> int: ...

class Region:
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def kind(self) -> str: ...

class Plan:
    @property
    def planner(self) -> str: ...
    @property
    def contract(self) -> str: ...
    @property
    def file_size(self) -> int: ...
    @property
    def regions(self) -> list[Region]: ...

class PlannedObject:
    @property
    def digest(self) -> str: ...
    @property
    def length(self) -> int: ...
    @property
    def kind(self) -> str: ...

class HashedPlan:
    @property
    def planner(self) -> str: ...
    @property
    def contract(self) -> str: ...
    @property
    def file_size(self) -> int: ...
    @property
    def objects(self) -> list[PlannedObject]: ...

class FileRecord:
    def __init__(self, kind: str, length: int, digest: str | None = None) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def digest(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @staticmethod
    def data(digest: str, length: int) -> FileRecord: ...
    @staticmethod
    def hole(length: int) -> FileRecord: ...

class SnapshotEntry:
    @property
    def path(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def executable(self) -> bool | None: ...
    @property
    def planner(self) -> str | None: ...
    @property
    def logical_size(self) -> int | None: ...
    @property
    def records(self) -> list[FileRecord] | None: ...
    @property
    def digest(self) -> str | None: ...
    @property
    def body_sha256(self) -> str | None: ...
    @property
    def target(self) -> str | None: ...
    @property
    def ordinal(self) -> int | None: ...

class Snapshot:
    @property
    def parent(self) -> str | None: ...
    @property
    def snapshot_id(self) -> str: ...
    @property
    def entries(self) -> list[SnapshotEntry]: ...
    def to_bytes(self) -> bytes: ...
    def file_records(self, path: str) -> list[FileRecord] | None: ...
    def ordinal_path(self, ordinal: int) -> str | None: ...

class PackObject:
    @property
    def digest(self) -> str: ...
    @property
    def data(self) -> bytes: ...
    @property
    def length(self) -> int: ...

class MappedObject:
    """One CAS object mapped read-only and exported as a C buffer.

    `memoryview(MappedObject(path))` addresses the mapped pages directly --
    that is the whole zero-copy claim, owned by the extension rather than by
    the facade. The buffer keeps a strong reference to the instance, so the
    mapping outlives every view taken of it.
    """

    def __init__(self, path: str | PathLike[str]) -> None: ...
    @property
    def path(self) -> Path: ...
    @property
    def length(self) -> int: ...
    def __len__(self) -> int: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...

class ObjectStore:
    def __init__(self, root: str | PathLike[str]) -> None: ...
    @property
    def root(self) -> Path: ...
    def put_bytes(self, data: bytes) -> AdmittedObject: ...
    def admit_file(
        self,
        path: str | PathLike[str],
        seams: str | None = None,
    ) -> tuple[Plan, list[AdmittedObject]]: ...
    def read_object(self, digest: str) -> bytes: ...
    def read_object_range(self, digest: str, offset: int, length: int) -> bytes: ...
    def verify(self, digest: str) -> int: ...
    def contains(self, digest: str) -> bool: ...
    def collect_abandoned_temps(self, grace_seconds: float) -> TempCollection: ...
    @property
    def supports_symlinks(self) -> bool: ...
    def project_snapshot(self, snapshot: Snapshot) -> Path: ...
    def remove_snapshot_tree(self, snapshot_id: str) -> bool: ...
    def set_ref(self, name: str, snapshot_id: str) -> None: ...
    def read_ref(self, name: str) -> str | None: ...
    def remove_ref(self, name: str) -> bool: ...

# `Verdict`, `Conversion` and `Mismatch` stood here. The v2 decision engine is
# Go-only and the hub owns the verdict, so there is no verdict to type across
# this boundary any more.

class ContractInfo:
    @property
    def name(self) -> str | None: ...
    @property
    def version(self) -> int | None: ...
    @property
    def description(self) -> str: ...
    @property
    def dtype(self) -> str | None: ...
    @property
    def digest(self) -> str: ...
    @property
    def stamp(self) -> str: ...

class StreamTensor:
    @property
    def name(self) -> str: ...
    @property
    def dtype(self) -> str: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def offset(self) -> int: ...
    @property
    def nbytes(self) -> int: ...

class FillStats:
    @property
    def source_bytes(self) -> int: ...
    @property
    def destination_bytes(self) -> int: ...
    @property
    def padding_bytes(self) -> int: ...
    @property
    def runs(self) -> int: ...
    @property
    def chunks(self) -> int: ...

class HostFillClient:
    def fill_address(
        self,
        source_ptr: int,
        source_bytes: int,
        destination_ptr: int,
        destination_bytes: int,
        shape: Sequence[int],
        element_bytes: int,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...
    def fill_files(
        self,
        records: Sequence[tuple[str | PathLike[str] | None, int, int]],
        destination_ptr: int,
        destination_bytes: int,
        shape: Sequence[int],
        element_bytes: int,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...

class CudaFillClient:
    def __init__(self, staging_bytes: int, device: int = 0) -> None: ...
    def fill(
        self,
        reader: TensorStreamReader,
        name: str,
        destination_ptr: int,
        destination_bytes: int,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...
    def fill_address(
        self,
        source_ptr: int,
        source_bytes: int,
        destination_ptr: int,
        destination_bytes: int,
        shape: Sequence[int],
        element_bytes: int,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...
    def fill_files(
        self,
        records: Sequence[tuple[str | PathLike[str] | None, int, int]],
        destination_ptr: int,
        destination_bytes: int,
        shape: Sequence[int],
        element_bytes: int,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...

class TensorStreamReader:
    def __init__(
        self,
        store: ObjectStore,
        records: Sequence[FileRecord],
        direct: bool = False,
    ) -> None: ...
    @property
    def tensors(self) -> list[StreamTensor]: ...
    @property
    def format(self) -> str: ...
    @property
    def length(self) -> int: ...
    @property
    def direct(self) -> bool: ...
    def readinto(
        self, offset: int, length: int, buffer: bytearray | memoryview
    ) -> int: ...
    def read_tensor_into(
        self, name: str, buffer: bytearray | memoryview
    ) -> int: ...
    def fill_host_into(
        self,
        name: str,
        buffer: bytearray | memoryview,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...
    def fill_host_address(
        self,
        name: str,
        destination_ptr: int,
        destination_bytes: int,
        destination_offset: int = 0,
        layout: str = "torch.contiguous@1",
    ) -> FillStats: ...

class RecordsReader:
    def __init__(self, store: ObjectStore, records: Sequence[FileRecord]) -> None: ...
    @property
    def length(self) -> int: ...
    def read_at(self, offset: int, length: int) -> bytes: ...
    def plan(self) -> Plan: ...

def decode_snapshot(data: bytes) -> Snapshot: ...
def rekey(
    store: ObjectStore,
    planner: str,
    records: Sequence[FileRecord],
    names: Mapping[str, str],
    contract: str | None = None,
) -> list[FileRecord]: ...
def subset(
    store: ObjectStore,
    planner: str,
    records: Sequence[FileRecord],
    names: Mapping[str, str],
    contract: str | None = None,
) -> list[FileRecord]: ...
def adopt(
    store: ObjectStore,
    planner: str,
    records: Sequence[FileRecord],
    seams: str | None = None,
) -> tuple[list[FileRecord], str]: ...
def derive(
    store: ObjectStore,
    planner: str,
    records: Sequence[FileRecord],
    source_contract: str,
    target_contract: str,
) -> tuple[list[FileRecord], str]: ...
def stub_bytes(body_sha256: str, size: int) -> bytes: ...
def parse_stub(data: bytes) -> tuple[str, int] | None: ...
def snapshot_id_of(data: bytes) -> str: ...
def decode_pack(data: bytes) -> list[PackObject]: ...
def encode_pack(objects: Sequence[tuple[str, bytes]]) -> bytes: ...
def plan_bytes(data: bytes) -> Plan: ...
def plan_and_hash_bytes(data: bytes) -> HashedPlan: ...
def plan_file(path: str | PathLike[str], seams: str | None = None) -> Plan: ...
def plan_and_hash_file(
    path: str | PathLike[str], seams: str | None = None
) -> HashedPlan: ...
def ingest_concurrency() -> int: ...
def contract_info(document: str) -> ContractInfo: ...
