//! Vendors the layout-morphism catalog INTO the crate.
//!
//! The catalog is portable ground truth — versioned JSON in this repo, read by
//! the Go decision engine and by this crate. Vendoring it at build time rather
//! than reading a directory at run time is the same ruling `catalog.go` makes
//! for the Go side and for the same reason: a fill path that could be pointed
//! at a different directory is a fill path that can be given a different
//! permutation than the hub decided with, and the two disagreeing is invisible
//! until a pod serves noise. The bytes ship with the engine or not at all.

use std::path::Path;

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../spec/v2/layouts");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut names: Vec<String> = std::fs::read_dir(&root)
        .unwrap_or_else(|error| panic!("layout catalog at {}: {error}", root.display()))
        .filter_map(|entry| {
            let name = entry.ok()?.file_name().to_string_lossy().into_owned();
            name.ends_with(".json").then_some(name)
        })
        .collect();
    // Sorted, so the generated order is the catalog's order and a rebuild on
    // another machine produces the same table.
    names.sort();
    assert!(
        !names.is_empty(),
        "the layout catalog at {} is empty",
        root.display()
    );

    let mut generated = String::from(
        "// @generated by build.rs from spec/v2/layouts. Do not edit.\n\
         pub(crate) static CATALOG: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        println!("cargo:rerun-if-changed={}", root.join(name).display());
        generated.push_str(&format!(
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../spec/v2/layouts/{name}\"))),\n"
        ));
    }
    generated.push_str("];\n");

    let out = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("layout_catalog.rs");
    std::fs::write(&out, generated).expect("write layout_catalog.rs");
}
